### ISSUE TITLE
error

### ISSUE THREAD

**Issue by darekjian** [haozi/New-Bing-Anywhere#102]
<pre>
Version: 2.1.4 
UA: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36
Lang: en-US
AcceptLangs: en-US, zh-CN, zh, en, zh-TW
config: {"showGoogleButtonOnBing":true,"showBingButtonOnGoogle":true,"showGuideToGithub":true,"showChat":true,"showRelease":true,"triggerMode":"Always","conversationStyle":"Balanced"}
engine: google
query: ANSYSLICMAN 2023 "download"
stack: Error: WebSocket `wss://sydney.bing.com/sydney/ChatHub` did not connect successfully.
</pre>

**Comment by haozi** [comment]
duplicated https://github.com/haozi/New-Bing-Anywhere/issues/101
