### ISSUE TITLE
Please add all google.* domain to site access

### ISSUE THREAD

**Issue by C3FF995BAE4** [haozi/New-Bing-Anywhere#108]
Currently only below 4 domains are listed:
http://*.bing.com/*
https://*.bing.com/*
https://www.google.com.hk/*
https://www.google.com/*

Please add all google.* domains such as:
*://*.google.ad/*
*://*.google.ae/*
*://*.google.al/*
*://*.google.am/*
*://*.google.as/*

Full list:
https://pastes.io/w2zp1menfp

**Comment by haozi** [comment]
The next version will be supported,  There might be prompts for permission changes. Don't panic.

See https://github.com/haozi/New-Bing-Anywhere/issues/24

**Comment by haozi** [comment]
Starting from version 2.2.1, we now offer support for them
