### ISSUE TITLE
可以新增2个功能吗？

### ISSUE THREAD

**Issue by Bian-Sh** [haozi/New-Bing-Anywhere#109]
1. 新增折叠历史记录，这个一直挂在右侧很碍眼占用篇幅，也会暴露隐私（比如截图时）
2. 可以通过 第三方风向 对话
下面是一个 开源的 newbing 历史记录处理的仓库，实现了对话分享，可以整合一下不？
谢谢~~

**Comment by haozi** [comment]
My foreign friends, If your Chinese is not good
, you can speak English. This repo does not only accept Chinese issues. There may be lot of users from China. They use my extension to bypass the network
