### ISSUE TITLE
反馈意见

### ISSUE THREAD

**Issue by zhlijia** [haozi/New-Bing-Anywhere#11]
我的微软账户已经通过了chat申请，但是通过这个插件还是不行

Version: 1.3.0
UA: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36
Lang: zh-CN
AcceptLangs: zh-CN, zh, en, zh-TW, und

**Comment by haozi** [comment]
https://github.com/haozi/New-Bing-Anywhere/issues/8

**Comment by RbRookie** [comment]
我的可以哎，是不是你的bing账号登录的问题

**Comment by haozi** [comment]
没有后续反馈，can't repro
