### ISSUE TITLE
装了插件不跳转 cn 二级域名了，但还是显示国内版/国际版

### ISSUE THREAD

**Issue by liweili273** [haozi/New-Bing-Anywhere#110]
<pre>
Version: 2.1.4 
UA: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36
Lang: zh-CN
AcceptLangs: zh-CN, zh, ru, en
config: {"showGoogleButtonOnBing":true,"showBingButtonOnGoogle":true,"showGuideToGithub":false,"showChat":true,"showRelease":true,"triggerMode":"Always","conversationStyle":"Balanced"}</pre>

**Comment by haozi** [comment]
https://github.com/haozi/New-Bing-Anywhere/issues/8
