### ISSUE TITLE
User needs to solve CAPTCHA to continue.

### ISSUE THREAD

**Issue by feiqingbiss** [haozi/New-Bing-Anywhere#112]
只要搜索内容就会出现要重复验证的问题， User needs to solve CAPTCHA to continue.

<pre>
Version: 2.1.4 
UA: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36
Lang: zh-CN
AcceptLangs: zh-CN, zh, en
config: {"showGoogleButtonOnBing":true,"showBingButtonOnGoogle":true,"showGuideToGithub":true,"showChat":true,"showRelease":true,"triggerMode":"Always","conversationStyle":"Balanced"}
engine: google
query: Windows 11 version 22H2 (updated July
stack: Error: User needs to solve CAPTCHA to continue.
</pre>
![image](https://github.com/haozi/New-Bing-Anywhere/assets/36787768/183388f9-9d10-4c49-9899-ab00cb290e8c)

**Comment by feiqingbiss** [comment]
正常访问bingai，侧边栏会一直出现问题，clash rules方式而不是全局模式，节点美国。

**Comment by haozi** [comment]
https://github.com/haozi/New-Bing-Anywhere/issues/93

**Comment by feiqingbiss** [comment]
如果自己打开BING AI 才会出现验证真人的窗口

**Comment by haozi** [comment]
1. Possibly a new account
2. The IP used is judged as a suspicious IP by cloudflare

This issue is closed because it's duplicate, go to  https://github.com/haozi/New-Bing-Anywhere/issues/93 to discuss
