### ISSUE TITLE
大陆无法访问

### ISSUE THREAD

**Issue by hopperhuang** [haozi/New-Bing-Anywhere#113]
Error: There seem to be some errors :Error: Failed to create session.Please ensure that the `https://www.bing.com/turing/conversation/create` request is accessible.

<pre>
Version: 2.1.4 
UA: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36
Lang: zh-CN
AcceptLangs: en, zh-CN, zh, zh-TW, zh-HK
config: {"showGoogleButtonOnBing":true,"showBingButtonOnGoogle":true,"showGuideToGithub":true,"showChat":true,"showRelease":true,"triggerMode":"Always","conversationStyle":"Balanced"}
engine: google
query: 111
stack: Error: WebSocket `wss://sydney.bing.com/sydney/ChatHub` did not connect successfully.
</pre>

**Comment by haozi** [comment]
就不能读一眼 README?

https://github.com/haozi/New-Bing-Anywhere/issues/8
