### ISSUE TITLE
Error: There seem to be some errors :Request is throttled. Please try again later.

### ISSUE THREAD

**Issue by SmileTan7711** [haozi/New-Bing-Anywhere#114]
<pre>
Version: 2.1.4 
UA: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36
Lang: zh-CN
AcceptLangs: zh-CN, en-US
config: {"showGoogleButtonOnBing":true,"showBingButtonOnGoogle":true,"showGuideToGithub":true,"showChat":true,"showRelease":true,"triggerMode":"Always","conversationStyle":"Balanced"}
engine: google
query: easy connect
stack: Error: Request is throttled. Please try again later.
</pre>

**Comment by haozi** [comment]
The request is throttled. Please try again later, or login another MS account

**Comment by SmileTan7711** [comment]
> The request is throttled. Please try again later, or login another MS account

Solved by switching to another MS account
