### ISSUE TITLE
无法使用

### ISSUE THREAD

**Issue by JcobCN** [haozi/New-Bing-Anywhere#117]
<pre>
Version: 2.1.4 
UA: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36 Edg/114.0.1823.82
Lang: zh-CN
AcceptLangs: zh-CN, en, en-GB, en-US
config: {"showGoogleButtonOnBing":true,"showBingButtonOnGoogle":true,"showGuideToGithub":true,"showChat":true,"showRelease":true,"triggerMode":"Always","conversationStyle":"Balanced"}
engine: google
query: bing ai
stack: Error: WebSocket `wss://sydney.bing.com/sydney/ChatHub` did not connect successfully.
</pre>

访问bing ai，会出现   Sorry, looks like your network settings are preventing access to this feature.
没有用任何的header修改器，确保bing的域名都走了proxy。
我另一台电脑，用的同样的proxy，是可以正常访问的。插件会自动更新，好像是自动更新后不行了，不知道是不是这个原因。

**Comment by haozi** [comment]
抓包看下这两个请求，确认是 否可以正常使用 [bing.com/new](https://www.bing.com/new) 官网的聊天功能
<img width="697" alt="image" src="https://github.com/haozi/New-Bing-Anywhere/assets/4150641/ee0208e1-a34a-479f-b1d8-1ec472ef4628">

**Comment by JcobCN** [comment]
![image](https://github.com/haozi/New-Bing-Anywhere/assets/19268110/3fabcc1d-0c38-410d-9d6f-c32f76bad9b3)
![image](https://github.com/haozi/New-Bing-Anywhere/assets/19268110/ebb562f5-c97f-4ac3-bf12-f34716e8ca80)


没看到chathub，只有create

**Comment by haozi** [comment]
看下create 的请求头

**Comment by JcobCN** [comment]
![image](https://github.com/haozi/New-Bing-Anywhere/assets/19268110/9c855764-f578-4770-8f96-a9888ae7fc78)
create请求头

**Comment by haozi** [comment]
截全点，大哥

**Comment by JcobCN** [comment]
请求头就这么多，26项，全在这了。
下面这个是响应头
![image](https://github.com/haozi/New-Bing-Anywhere/assets/19268110/08afe3fc-eb58-4195-a8f5-90d84efb68ae)

**Comment by haozi** [comment]
https://www.bing.com/search?q=Bing+AI&showconv=1 能正常聊天吗

**Comment by JcobCN** [comment]
![image](https://github.com/haozi/New-Bing-Anywhere/assets/19268110/422e877e-b4ac-489c-89b7-5ffb8a2b16e7)
不能

**Comment by haozi** [comment]
。。。 换 ip,或者试着开启下  "Dangerous Request Forgery" 选项，下面的内容稍微读一下啊哥


![image](https://github.com/haozi/New-Bing-Anywhere/assets/4150641/c30a09bb-c59a-4d17-b436-79538e231320)

**Comment by JcobCN** [comment]
我没别的ip了，家里笔记本能用。公司电脑刚开始可以，后面就不行了，很奇怪。用的都是同一个代理，美国的vps。
那个选项我也试过，不起作用。

**Comment by haozi** [comment]
你那很明显的就是网络问题
