### ISSUE TITLE
Issue with Chat sidebar

### ISSUE THREAD

**Issue by aryalmilan100** [haozi/New-Bing-Anywhere#118]
<pre>
Version: 2.1.4 
UA: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36
Lang: en-US
AcceptLangs: en-US, en
config: {"showGoogleButtonOnBing":true,"showBingButtonOnGoogle":true,"showGuideToGithub":true,"showChat":true,"showRelease":true,"triggerMode":"Always","conversationStyle":"Balanced"}
engine: google
query: bl fantasy
stack: Error: User needs to solve CAPTCHA to continue.
</pre>

**Comment by haozi** [comment]
https://github.com/haozi/New-Bing-Anywhere/issues/8

![image](https://github.com/haozi/New-Bing-Anywhere/assets/4150641/f1bbcfe5-0fef-4df7-8d7b-f6c26612fc84)

**Comment by haozi** [comment]
go to https://www.bing.com/search?q=Bing+AI&showconv=1 , send a message to resolve CAPTCHA
