### ISSUE TITLE
Extension not working on Opera for linux

### ISSUE THREAD

**Issue by sebinllas** [haozi/New-Bing-Anywhere#120]
<pre>
Version: 2.1.4 
UA: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36 OPR/100.0.0.0
Lang: en-US
AcceptLangs: es-CO, en
config: {"showGoogleButtonOnBing":true,"showBingButtonOnGoogle":true,"showGuideToGithub":true,"showChat":true,"showRelease":true,"triggerMode":"Always","conversationStyle":"Balanced"}</pre>

**Comment by haozi** [comment]
![IMG_0966](https://github.com/haozi/New-Bing-Anywhere/assets/4150641/5544cb3d-8bc0-4373-a97d-703c92ab7f21)
