### ISSUE TITLE
Error: Request is throttled. Please try again later.

### ISSUE THREAD

**Issue by GaiJinn** [haozi/New-Bing-Anywhere#123]
<pre>
Version: 2.1.4 
UA: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36
Lang: en-US
AcceptLangs: en-US, en, zh-CN, de
config: {"showGoogleButtonOnBing":true,"showBingButtonOnGoogle":true,"showGuideToGithub":true,"showChat":true,"showRelease":true,"triggerMode":"Always","conversationStyle":"Balanced"}
engine: google
query: 水潭人院
stack: Error: Request is throttled. Please try again later.
</pre>

**Comment by haozi** [comment]
stack: Error: Request is throttled. Please try again later.
