### ISSUE TITLE
the problem of Newbing Bar

### ISSUE THREAD

**Issue by mingzhimuren** [haozi/New-Bing-Anywhere#125]
<pre>
Version: 2.2.1 
UA: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36
Lang: zh-CN
AcceptLangs: zh-CN, en, en-GB, en-US, ja, zh-TW
config: {"showGoogleButtonOnBing":true,"showBingButtonOnGoogle":true,"showGuideToGithub":true,"showChat":true,"showRelease":true,"triggerMode":"Always","conversationStyle":"Balanced"}
engine: google
query: テレビ東京 韓国ドラマ
stack: Error: WebSocket `wss://sydney.bing.com/sydney/ChatHub` did not connect successfully.
</pre>

**Comment by haozi** [comment]
have you login bing.com？

**Comment by haozi** [comment]
https://github.com/haozi/New-Bing-Anywhere/issues/117
