### ISSUE TITLE
没有出现bing ai界面

### ISSUE THREAD

**Issue by kinghua1** [haozi/New-Bing-Anywhere#128]
<pre>
Version: 2.2.1 
UA: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36 Edg/115.0.1901.183
Lang: zh-CN
AcceptLangs: zh-CN, en
config: {"showGoogleButtonOnBing":true,"showBingButtonOnGoogle":true,"showGuideToGithub":false,"showChat":true,"showRelease":true,"triggerMode":"Always","conversationStyle":"Balanced"}</pre>

**Comment by haozi** [comment]
try open  "Dangerous Request Forgery" option
