### ISSUE TITLE
不能使用

### ISSUE THREAD

**Issue by kksailon** [haozi/New-Bing-Anywhere#129]
![image](https://github.com/haozi/New-Bing-Anywhere/assets/40158343/3ae5247c-9277-45ce-b646-ec3c40266e55)

<pre>
Version: 2.2.1 
UA: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36
Lang: zh-CN
AcceptLangs: zh-TW, zh, zh-CN, en, en-US
config: {"showGoogleButtonOnBing":true,"showBingButtonOnGoogle":true,"showGuideToGithub":true,"showChat":true,"showRelease":true,"triggerMode":"Always","conversationStyle":"Balanced"}</pre>

**Comment by haozi** [comment]
https://github.com/haozi/New-Bing-Anywhere/issues/8#issuecomment-1639228689

![image](https://github.com/haozi/New-Bing-Anywhere/assets/4150641/383f0e91-9992-4ca5-828a-5e3f8551d836)
