### ISSUE TITLE
失败

### ISSUE THREAD

**Issue by Bruce230406** [haozi/New-Bing-Anywhere#13]
失败，还是国内BING失败，还是国内BING

![image](https://user-images.githubusercontent.com/129989907/230168779-c4453e86-1d40-46d0-b5ca-d09f19abebc5.png)

Version: 1.4.0
UA: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36 Edg/111.0.1661.62
Lang: zh-CN
AcceptLangs: zh-CN, en, en-GB, en-US

**Comment by haozi** [comment]
https://github.com/haozi/New-Bing-Anywhere/issues/8

**Comment by haozi** [comment]
The description is not informative enough. Please follow to the FAQ https://github.com/haozi/New-Bing-Anywhere/issues/8 to check the problem. 

Let's temporarily close this for now.
