### ISSUE TITLE
 Error: The conversationSignature is not set and is required to ensure that you have permission to use our APIs. IsAuthenticated=False. App ID=

### ISSUE THREAD

**Issue by Icemans007** [haozi/New-Bing-Anywhere#131]
<pre>
Version: 2.2.1 
UA: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36
Lang: zh-CN
AcceptLangs: zh-CN, zh, en
config: {"showGoogleButtonOnBing":true,"showBingButtonOnGoogle":true,"showGuideToGithub":false,"showChat":true,"showRelease":true,"triggerMode":"Always","conversationStyle":"Balanced"}
engine: google
query: 电影蜂蜜
stack: Error: The conversationSignature is not set and is required to ensure that you have permission to use our APIs. IsAuthenticated=False. App ID=
</pre>

**Comment by haozi** [comment]
refresh and retry
