### ISSUE TITLE
Error: User needs to solve CAPTCHA to continue.

### ISSUE THREAD

**Issue by cloud37wind** [haozi/New-Bing-Anywhere#132]
<pre>
Version: 2.2.1 
UA: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36
Lang: zh-CN
AcceptLangs: zh
config: {"showGoogleButtonOnBing":true,"showBingButtonOnGoogle":true,"showGuideToGithub":false,"showChat":true,"showRelease":true,"triggerMode":"Always","conversationStyle":"Balanced"}
engine: google
query: nginx配置教程
stack: Error: User needs to solve CAPTCHA to continue.
</pre>

**Comment by haozi** [comment]
https://github.com/haozi/New-Bing-Anywhere/issues/93
