### ISSUE TITLE
一直都是尝试连接状态

### ISSUE THREAD

**Issue by gquo** [haozi/New-Bing-Anywhere#133]
![image](https://github.com/haozi/New-Bing-Anywhere/assets/129266179/30df1724-6895-4a92-9970-409df16128ab)

<pre>
Version: 2.2.1 
UA: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36 Edg/116.0.0.0
Lang: zh-CN
AcceptLangs: zh-CN, en, en-GB, en-US
config: {"showGoogleButtonOnBing":true,"showBingButtonOnGoogle":true,"showGuideToGithub":true,"showChat":true,"showRelease":true,"triggerMode":"Always","conversationStyle":"Balanced"}</pre>

**Comment by haozi** [comment]
Your IP has been banned, try to switch to a different IP.
