### ISSUE TITLE
new bing 无法在谷歌上使用

### ISSUE THREAD

**Issue by Ivonnelian** [haozi/New-Bing-Anywhere#135]
<pre>
Version: 2.2.1 
UA: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36
Lang: zh-CN
AcceptLangs: zh-CN, zh, en
config: {"showGoogleButtonOnBing":true,"showBingButtonOnGoogle":true,"showGuideToGithub":true,"showChat":true,"showRelease":true,"triggerMode":"Always","conversationStyle":"Creative"}
engine: google
query: weijibaike
stack: Error: Request is throttled. Please try again later.
</pre>

**Comment by haozi** [comment]
被微软限流了，错误信息已经很清晰了
Request is throttled. Please try again later.
 
 换帐号或换 ip
