### ISSUE TITLE
【2.21】chrome自动停用插件，该程序现在可以：读取和更改您在一些网站上的数据

### ISSUE THREAD

**Issue by kakapas** [haozi/New-Bing-Anywhere#136]
由于最新版的"New Bing Anywhere (Bing Chat GPT-4)"需要更多权限，因此已将其停用。

该程序现在可以：
读取和更改您在一些网站上的数据

-所有 aiplus.lol 网站
-所有 bing.com 网站
-所有 mail.ru 网站
-所有 openai.com 网站
-所有 search.yahoo.com 网站
-所有 sogou.com 网站
-所有 yandex.com 网站
-duckduckgo. com
-search.aol.com
-search.brave.com
-search.naver.com
-search.seznam.cz
-search.yahoo.co.jp
-so.toutiao. com
-www.ask.com
-www.baidu.com
-www.bing.com
-www.ecosia.org
-www.google.com
-www.so.com
-www.startpage.com

屏蔽所有页面上的内容

**Comment by haozi** [comment]
https://github.com/haozi/New-Bing-Anywhere/issues/24

发了这么久的公告都不能看一下的吗？
