### ISSUE TITLE
error

### ISSUE THREAD

**Issue by fbbDirge** [haozi/New-Bing-Anywhere#137]
<pre>
Version: 2.2.1 
UA: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36
Lang: zh-CN
AcceptLangs: zh-CN, zh, en
config: {"showGoogleButtonOnBing":true,"showBingButtonOnGoogle":true,"showGuideToGithub":false,"showChat":true,"showRelease":true,"triggerMode":"Always","conversationStyle":"Balanced"}
engine: google
query: 女子在南京地铁车厢喝水被开罚单
stack: Error: WebSocket `wss://sydney.bing.com/sydney/ChatHub` did not connect successfully.
</pre>

**Comment by haozi** [comment]
https://github.com/haozi/New-Bing-Anywhere/issues/130
