### ISSUE TITLE
无法使用

### ISSUE THREAD

**Issue by maxy0524** [haozi/New-Bing-Anywhere#14]
Version: 1.5.0
UA: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36
Lang: en-US
AcceptLangs: en-US, en, zh-CN

**Comment by haozi** [comment]
The description is not informative enough. Please follow to the FAQ https://github.com/haozi/New-Bing-Anywhere/issues/8 to check the problem. 

Let's temporarily close this for now.

If you have more information, you can reopen this issue or join the Telegram group for further discussion.
