### ISSUE TITLE
闭包的使用

### ISSUE THREAD

**Issue by sun988888888** [haozi/New-Bing-Anywhere#141]
<pre>
Version: 2.2.1 
UA: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36
Lang: zh-CN
AcceptLangs: zh-CN, zh
config: {"showGoogleButtonOnBing":true,"showBingButtonOnGoogle":true,"showGuideToGithub":true,"showChat":true,"showRelease":true,"triggerMode":"Always","conversationStyle":"Balanced"}
engine: google
query: 测试
stack: Error: Error: Failed to create session.Please ensure that the `https://www.bing.com/turing/conversation/create` request is accessible.
</pre>

**Comment by haozi** [comment]
Error: Failed to create session.Please ensure that the `https://www.bing.com/turing/conversation/create` request is accessible
