### ISSUE TITLE
狐猴浏览器失效了

### ISSUE THREAD

**Issue by clock8863** [haozi/New-Bing-Anywhere#142]
<pre>
Version: 2.2.1 
UA: Mozilla/5.0 (Linux; Android 13; 23046RP50C) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36
Lang: zh-CN
AcceptLangs: zh-CN, zh
config: {"showGoogleButtonOnBing":true,"showBingButtonOnGoogle":true,"showGuideToGithub":true,"showChat":false,"showRelease":true,"triggerMode":"Always","conversationStyle":"Balanced"}</pre>

**Comment by haozi** [comment]
https://github.com/haozi/New-Bing-Anywhere/issues/8
<img width="916" alt="image" src="https://github.com/haozi/New-Bing-Anywhere/assets/4150641/f88787c4-07f9-45c4-81d4-1b4d8b9997aa">
