### ISSUE TITLE
a new bing's question,WebSocket `wss://sydney.bing.com/sydney/ChatHub` did not connect successfully.

### ISSUE THREAD

**Issue by swc2020-max** [haozi/New-Bing-Anywhere#144]
<pre>
Version: 2.2.1 
UA: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36
Lang: zh-CN
AcceptLangs: zh-CN, zh
config: {"showGoogleButtonOnBing":true,"showBingButtonOnGoogle":true,"showGuideToGithub":false,"showChat":true,"showRelease":true,"triggerMode":"Always","conversationStyle":"Balanced"}
engine: google
query: Invalid CAPTCHA response, please try again
stack: Error: WebSocket `wss://sydney.bing.com/sydney/ChatHub` did not connect successfully.
</pre>

**Comment by haozi** [comment]
https://github.com/haozi/New-Bing-Anywhere/issues/8
