### ISSUE TITLE
退款

### ISSUE THREAD

**Issue by okucdty** [haozi/New-Bing-Anywhere#146]
非常抱歉我认错了你的插件，我认为你的插件就是bing的嵌套的AI，所以我在里面付了款项，但是我发现你用的GPT模型不是4.0版本的，所以我要求退款。三十五元，我的支付宝账号是15069227591.

<pre>
Version: 2.2.1 
UA: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36 Edg/115.0.1901.183
Lang: zh-CN
AcceptLangs: zh-CN, en, en-GB, en-US
config: {"showGoogleButtonOnBing":true,"showBingButtonOnGoogle":true,"showGuideToGithub":true,"showChat":false,"showRelease":true,"triggerMode":"Always","conversationStyle":"Balanced"}</pre>

**Comment by alt-0191** [comment]
？
