### ISSUE TITLE
想要new bing anywhere for firefox

### ISSUE THREAD

**Issue by xhgc** [haozi/New-Bing-Anywhere#15]
个人用Firefox习惯了，看到作者有打算把Firefox的new bing anywhere列入计划中，所以我就来催个更~~

**Comment by haozi** [comment]
Thank you for your suggestions. We have a plan to support it. Please stay tuned for our updates.

**Comment by haozi** [comment]
The Firefox version has been uploaded to the Mozilla-Market

https://addons.mozilla.org/firefox/addon/new-bing-anywhere/
