### ISSUE TITLE
请停止自动打开页面，不要跳转 github 主页

### ISSUE THREAD

**Issue by mengjincc** [haozi/New-Bing-Anywhere#150]
正在演示的时候突然跳转到github 页面，请停止该行为，谢谢

<pre>
Version: 2.3.0 
UA: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36
Lang: zh-CN
AcceptLangs: zh-CN, zh
config: {"showGoogleButtonOnBing":true,"showBingButtonOnGoogle":true,"showGuideToGithub":false,"showChat":true,"showRelease":true,"triggerMode":"Always","conversationStyle":"Balanced"}</pre>

**Comment by haozi** [comment]
不能看一下 options 里的配置项吗

**Comment by Bian-Sh** [comment]
这里有个逻辑，就是每次更新后就会/才会跳转到 GitHub 页面，你可以在配置页面关闭自动更新
