### ISSUE TITLE
可能需要更新浏览器标识了，issue #8 中 第五条看到的不是你截图中的内容。

### ISSUE THREAD

**Issue by Bian-Sh** [haozi/New-Bing-Anywhere#151]
Newbing 聊天不能用，显示：“Sorry, looks like your network settings are preventing access to this feature.”
![image](https://github.com/haozi/New-Bing-Anywhere/assets/24520547/6059201f-6792-4982-b42f-1e9b22431022)

sidebar 也不能使用，错误如下：
<pre>
Version: 2.3.0 
UA: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36
Lang: zh-CN
AcceptLangs: zh-CN, zh
config: {"showGoogleButtonOnBing":true,"showBingButtonOnGoogle":true,"showGuideToGithub":true,"showChat":true,"showRelease":true,"triggerMode":"Always","conversationStyle":"Balanced"}
engine: google
query: 115
stack: Error: WebSocket `wss://sydney.bing.com/sydney/ChatHub` did not connect successfully.
</pre>

我的尝试：

已经清了缓存，清了 cookie.

按照 issue #8 中 第五条，看到配图与你给的不一致，如下：
![image](https://github.com/haozi/New-Bing-Anywhere/assets/24520547/cd4b977a-3039-4330-9f11-414c29fb8d7e)
会是插件需要需要更新浏览器标识了？

其他信息：
Edge 下 newbing 可用的，所以代理啥的应该是没问题。

**Comment by Bian-Sh** [comment]
![image](https://github.com/haozi/New-Bing-Anywhere/assets/24520547/d9fd4722-e14f-42f5-bc00-6851043563b1)
zh这是我现在保留的插件，仅供参考

**Comment by haozi** [comment]
谢谢，必应改UI了

**Comment by haozi** [comment]
https://github.com/haozi/New-Bing-Anywhere/issues/117

参考下这个

**Comment by Bian-Sh** [comment]
> #117
> 
> 参考下这个

emmm 我使用 *.bing.com ，改为bing.com sydney.bing.com 分别写入配置好像又能了

**Comment by Bian-Sh** [comment]
在什么情况下，https://www.bing.com/search?q=Bing+AI&showconv=1&FORM=hpcodx 能够对话，但是 sidebar 会出现下面的报错呢?
是超时检测时间太短了不？
![image](https://github.com/haozi/New-Bing-Anywhere/assets/24520547/fe011b0d-8160-4248-a06c-c2fb051c1e8f)

**Comment by haozi** [comment]
看来微软又恢复了

![image](https://github.com/haozi/New-Bing-Anywhere/assets/4150641/00e1e0f4-2cc9-4bd3-889a-45f407142f87)
