### ISSUE TITLE
love

### ISSUE THREAD

**Issue by Yoss654** [haozi/New-Bing-Anywhere#154]
<pre>
Version: 2.3.0 
UA: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36
Lang: fr
AcceptLangs: en-MA, fr-MA, fr, en-US, en
config: {"showGoogleButtonOnBing":true,"showBingButtonOnGoogle":true,"showGuideToGithub":true,"showChat":true,"showRelease":true,"triggerMode":"Always","conversationStyle":"Balanced"}
engine: google
query: love
stack: Error: User needs to solve CAPTCHA to continue.
</pre>

**Comment by haozi** [comment]
please read  https://github.com/haozi/New-Bing-Anywhere/issues/8 first, Thanks.

https://github.com/haozi/New-Bing-Anywhere/issues/93#issuecomment-1639174881

The CAPTCHA challenge is difficult to solve. Microsoft has outsourced it to Cloudflare, so the only way to resolve it is within Bing's own chat box.

go to https://www.bing.com/search?q=Bing+AI&showconv=1 , send a message to resolve CAPTCHA
