### ISSUE TITLE
科学上网后进入bing仍然是国内版/国际版

### ISSUE THREAD

**Issue by zhuhw0916** [haozi/New-Bing-Anywhere#16]
使用的是日本节点，天气也显示的是京都，cookie缓存也清理过，但仍然是国内版/国际版界面，十分困惑。
我的微软账号是用国内大学电子邮箱注册的，这问题是不是与微软账号有关？

Version: 1.5.1
UA: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36 Edg/112.0.1722.34
Lang: zh-CN
AcceptLangs: zh-CN, en, en-GB, en-US

**Comment by haozi** [comment]
Try switching your account, IP, and browser and retry.
Try changing your operating system language and region to a non-mainland region.
You can also join the Telegram group for communication.

**Comment by hiwasax** [comment]
是的，之前可以，现在突然就不行了。

**Comment by zhuhw0916** [comment]
> Try switching your account, IP, and browser and retry. Try changing your operating system language and region to a non-mainland region. You can also join the Telegram group for communication.



> 是的，之前可以，现在突然就不行了。

十分感谢你的热情回答，也十分感谢作者，我再去尝试一下

**Comment by hiwasax** [comment]
亲，收到您的邮件很心，我会尽快打开阅读，同时也会尽快回复您。

**Comment by brianjojoray** [comment]
今天开始所有方法都失效了，不论如何都会被重定向到国内版

**Comment by haozi** [comment]
The problem has been identified and Microsoft has upgraded their policy. Version 1.5.2 has been released and is currently under review.
Temporary solution:
Enter the following command in the Console:
```
document.cookie = '_RwBf=wls=2'
```
<img width="444" alt="image" src="https://user-images.githubusercontent.com/4150641/232027145-6e3b98f1-1868-4dad-87b4-6cc87fef0aca.png">

**Comment by klein2000** [comment]
> The problem has been identified and Microsoft has upgraded their policy. Version 1.5.2 has been released and is currently under review. Temporary solution: Enter the following command in the Console:
> 
> ```
> document.cookie = '_RwBf=wls=2'
> ```
> 
> <img alt="image" width="444" src="https://user-images.githubusercontent.com/4150641/232027145-6e3b98f1-1868-4dad-87b4-6cc87fef0aca.png">

still confused how and when to use the temporary solution.  Bing still forced a redirection to cn.bing no matter I typed in the command in F12 mode before or after accessing bing. could you elaborate a little more on the right procedure?

**Comment by haozi** [comment]
Try disable all your another extensions

**Comment by haozi** [comment]
> > The problem has been identified and Microsoft has upgraded their policy. Version 1.5.2 has been released and is currently under review. Temporary solution: Enter the following command in the Console:
> > ```
> > document.cookie = '_RwBf=wls=2'
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > <img alt="image" width="444" src="https://user-images.githubusercontent.com/4150641/232027145-6e3b98f1-1868-4dad-87b4-6cc87fef0aca.png">
> 
> still confused how and when to use the temporary solution. Bing still forced a redirection to cn.bing no matter I typed in the command in F12 mode before or after accessing bing. could you elaborate a little more on the right procedure?

https://github.com/haozi/New-Bing-Anywhere/issues/8
