### ISSUE TITLE
error

### ISSUE THREAD

**Issue by wqm110** [haozi/New-Bing-Anywhere#160]
<pre>
Version: 2.3.0 
UA: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36
Lang: zh-CN
AcceptLangs: zh-CN, zh
config: {"showGoogleButtonOnBing":true,"showBingButtonOnGoogle":true,"showGuideToGithub":false,"showChat":true,"showRelease":true,"triggerMode":"Always","conversationStyle":"Balanced"}
engine: google
query: swift 视频
stack: Error: WebSocket `wss://sydney.bing.com/sydney/ChatHub` did not connect successfully.
</pre>

**Comment by haozi** [comment]
https://github.com/haozi/New-Bing-Anywhere/issues/117
