### ISSUE TITLE
有时候就是连不上

### ISSUE THREAD

**Issue by songofhawk** [haozi/New-Bing-Anywhere#162]
这是个蜜汁问题：一般情况下可用，但有时就是连不上，换了节点也不行（此节点上 openai 是可以的）

<pre>
Version: 2.3.0 
UA: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36
Lang: zh-CN
AcceptLangs: zh-CN, zh, af, en, zh-TW
config: {"showGoogleButtonOnBing":true,"showBingButtonOnGoogle":true,"showGuideToGithub":true,"showChat":true,"showRelease":true,"triggerMode":"Always","conversationStyle":"Balanced"}
engine: google
query: 精简的 英文
stack: Error: WebSocket `wss://sydney.bing.com/sydney/ChatHub` did not connect successfully.
</pre>

**Comment by haozi** [comment]
#117
