### ISSUE TITLE
没问题

### ISSUE THREAD

**Issue by aotine** [haozi/New-Bing-Anywhere#164]
没问题

<pre>
Version: 2.3.0 
UA: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36
Lang: zh-CN
AcceptLangs: zh-CN, zh
config: {"showGoogleButtonOnBing":true,"showBingButtonOnGoogle":true,"showGuideToGithub":false,"showChat":true,"showRelease":true,"triggerMode":"Always","conversationStyle":"Balanced"}
engine: google
query: 电影
stack: Error: Cannot retrieve user status.
</pre>

**Comment by haozi** [comment]
麻烦描述清楚问题，互相尊重一下，谢谢
