### ISSUE TITLE
提示Sorry, looks like your network settings are preventing access to this feature.

### ISSUE THREAD

**Issue by CloudBank-3055** [haozi/New-Bing-Anywhere#17]
已科学上网，关闭插件时能正常使用NEW BING侧边栏，但开启此插件后后提示Sorry, looks like your network settings are preventing access to this feature.
个人推测插件还需要更改DNS为1.1.1.1或者其他可用的DNS

Version: 1.5.1
UA: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36 Edg/112.0.1722.39
Lang: zh-CN
AcceptLangs: zh-CN, en

**Comment by haozi** [comment]
Try with other extensions that can modify request headers together, could you take more screenshots.

**Comment by CloudBank-3055** [comment]
抱歉，我没法复现这个问题。或许在启用此插件时清除bing.com的cookie能预防有关问题？
