### ISSUE TITLE
不明白

### ISSUE THREAD

**Issue by jiangliushi666** [haozi/New-Bing-Anywhere#170]
<pre>
Version: 2.3.0 
UA: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36
Lang: zh-CN
AcceptLangs: zh-CN, zh
config: {"showGoogleButtonOnBing":true,"showBingButtonOnGoogle":true,"showGuideToGithub":true,"showChat":true,"showRelease":true,"triggerMode":"Always","conversationStyle":"Balanced"}
engine: google
query: isilon的单个文件大小是不是16T，powerscale的单个文件大小限制，不是文件系统限制
stack: Error: Cannot retrieve user status.
</pre>

**Comment by haozi** [comment]
#8
