### ISSUE TITLE
Chrome中安装插件后并不能使用chat

### ISSUE THREAD

**Issue by Ximu-Luya** [haozi/New-Bing-Anywhere#19]
Version: 1.5.2
UA: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36
Lang: zh-CN
AcceptLangs: zh-CN, zh, en

**Comment by Ximu-Luya** [comment]
搜索edge download后，并未显示已在Edge浏览中

**Comment by Ximu-Luya** [comment]
请问还需要提供什么信息，自查手册已看完，并不能解决问题

**Comment by NI-077** [comment]
我这里也有同样的情况！

**Comment by wuhua111** [comment]
这个我解决了，打开newbing的网页后如果弹出不能用的话，注意看右上角账号logo的旁边是不是有english，点击english把页面切换成英语，然后就可以愉快的聊天了。如果你想切换回中文，再在右上角三条横线图标那个按钮里的setting按钮里面就可以切换回中文了，并且还能够使用ai chat

**Comment by wuhua111** [comment]
> 请问还需要提供什么信息，自查手册已看完，并不能解决问题
这个我解决了,虽然不知道为什么。方法是，打开newbing的网页后如果弹出不能用的话，注意看右上角账号logo的旁边是不是有english，点击english把页面切换成英语，然后就可以愉快的聊天了。如果你想切换回中文，再在右上角三条横线图标那个按钮里的setting按钮里面就可以切换回中文了，并且还能够使用ai chat

**Comment by Ximu-Luya** [comment]
> > 请问还需要提供什么信息，自查手册已看完，并不能解决问题
> > 这个我解决了,虽然不知道为什么。方法是，打开newbing的网页后如果弹出不能用的话，注意看右上角账号logo的旁边是不是有english，点击english把页面切换成英语，然后就可以愉快的聊天了。如果你想切换回中文，再在右上角三条横线图标那个按钮里的setting按钮里面就可以切换回中文了，并且还能够使用ai chat

试了你这个办法，我这里还是不行，我自己去用插件修改请求头的user-agent也失效了，是不是微软也把这个操作也给修了，变成不通过请求体获取所在浏览器了。

**Comment by haozi** [comment]
什么版本的浏览器，ua 信息不一定准确，多发些截图吧

**Comment by loserzhu** [comment]
> 什么版本的浏览器，ua 信息不一定准确，多发些截图吧


Version: 1.5.2
UA: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36
Lang: en-US
AcceptLangs: en, zh-CN
另外
OS: win 10
chrome version: Version 112.0.5615.121 (Official Build) (64-bit)
运行在匿名窗口,其他插件也列出来了,没有启用油猴脚本,所以冲突的可能性较小.同样无效🧐

**screenshot**
<img width="1440" src="https://user-images.githubusercontent.com/25484581/232800350-d3944b55-0ad2-4054-884a-9861f009a2be.png" />

**Comment by haozi** [comment]
禁用adblock试试，你隐私下也开了好几个插件呀，如果会抓包，可以截图看一下请求头中的ua
搜索edge下载或edge download看是否提示你已经使用edge了

**Comment by haozi** [comment]
试一下火狐的版本，已经1.7.0了，Chrome还没推送

**Comment by Ximu-Luya** [comment]
Sorry啊，我仅打算在Chrome上使用，电脑上也没有火狐。那我就静待推送吧

**Comment by zbz0425** [comment]
> Sorry啊，我仅打算在Chrome上使用，电脑上也没有火狐。那我就静待推送吧

不是发布1.7.0了，直接下载源码包，解压后，在dist里面有个chromium文件夹，你chrome进入管理扩展页面，右上角选择开发者模式，然后左上角通过加载已解压的扩展程序 选择chromium文件夹即可啊。
<img width="1500" alt="image" src="https://user-images.githubusercontent.com/6782435/232869956-855e156c-5894-458c-af26-831d1535fec4.png">

**Comment by hzw1199** [comment]
https://learn.microsoft.com/en-us/microsoft-edge/web-platform/user-agent-guidance
模拟新版Edge添加header：
sec-ch-ua
"Chromium";v="112", "Microsoft Edge";v="112", "Not:A-Brand";v="99"

**Comment by haozi** [comment]
> > Sorry啊，我仅打算在Chrome上使用，电脑上也没有火狐。那我就静待推送吧
> 
> 不是发布1.7.0了，直接下载源码包，解压后，在dist里面有个chromium文件夹，你chrome进入管理扩展页面，右上角选择开发者模式，然后左上角通过加载已解压的扩展程序 选择chromium文件夹即可啊。
> 
> <img alt="image" width="1500" src="https://user-images.githubusercontent.com/6782435/232869956-855e156c-5894-458c-af26-831d1535fec4.png">
> 
> <img alt="image" width="1791" src="https://user-images.githubusercontent.com/4150641/232924775-afa5c471-7ac8-4020-b0b3-25c8c203efcd.png">

https://github.com/haozi/New-Bing-Anywhere/issues/21#issuecomment-1513861917

**Comment by haozi** [comment]
1.8.1版本已正式上架Google市场
