### ISSUE TITLE
Chrome always pops up a window to use the Edge browser. 始终弹窗使用edge浏览器

### ISSUE THREAD

**Issue by cr763092** [haozi/New-Bing-Anywhere#21]
4月18号下午开始，打开newbing链接始终弹窗使用edge浏览器。已翻墙，搜索天气显示墙外的地址。但是搜索安装edge仍然提示安装，应该怎么办呢？仅开启了您制作的插件，没有其他插件，清空浏览器的数据也不行。

Version: 1.5.2
UA: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36
Lang: zh-CN
AcceptLangs: zh-CN, zh, en-US, en

**Comment by wujarvis** [comment]
+1，也突然发现用不了了

**Comment by lgc2333** [comment]
+1

**Comment by pluto0x0** [comment]
+1 应该是bing做了调整

**Comment by hughli-git** [comment]
+1

**Comment by cr763092** [comment]
已经解决了，昨晚提交问题，半夜就解决了，太厉害了！

**Comment by haozi** [comment]
> 已经解决了，昨晚提交问题，半夜就解决了，太厉害了！

之前就预判到这个问题了，ff 版本发得快，Chrome审核时间长

**Comment by haozi** [comment]
1.8.1版本已正式上架Google市场
