### ISSUE TITLE
显示要求我在edge中打开

### ISSUE THREAD

**Issue by BLSM3344** [haozi/New-Bing-Anywhere#22]
显示要求我在edge中打开

Version: 1.5.2
UA: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36
Lang: zh-CN
AcceptLangs: zh-CN, zh

**Comment by BLSM3344** [comment]
chrom版本：Chrome 已是最新版本
版本 112.0.5615.138（正式版本） （64 位）

**Comment by haozi** [comment]
https://github.com/haozi/New-Bing-Anywhere/issues/21

**Comment by haozi** [comment]
1.8.1版本已正式上架Google市场
