### ISSUE TITLE
the new bing anywhere can't work now

### ISSUE THREAD

**Issue by batugao** [haozi/New-Bing-Anywhere#23]
Dear Author,

the enxtenstion can't work right now. It did work this afternoon when I set it up first time. But now, it can't work anymore. when I click new bing from extension, the page turned to new bing but asked to open Edge. 

Version: 1.5.2
UA: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36
Lang: en-GB
AcceptLangs: en, zh-CN, zh, ja, zh-TW
![1](https://user-images.githubusercontent.com/44385910/233400425-f3638204-f2a6-4a38-94ff-3ba7fea51127.png)
![2](https://user-images.githubusercontent.com/44385910/233400449-93d1fcaa-473e-4a66-86b1-1051ccab362e.png)

**Comment by batugao** [comment]
I'm in office network and not in china local network.

**Comment by haozi** [comment]
see https://github.com/haozi/New-Bing-Anywhere/issues/21

the latest version 1.7.0 of chromium is being reviewed by Google，As a temporary solution, you can download the zip package and install it locally

**Comment by batugao** [comment]
waiting for the latest version v1.7.0 to release.

**Comment by batugao** [comment]
Issue fixed by v1.8
