### ISSUE TITLE
chrome中使用失效了啊

### ISSUE THREAD

**Issue by Jorende** [haozi/New-Bing-Anywhere#25]
Version: 1.5.2
UA: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36
Lang: zh-CN
AcceptLangs: zh-CN, zh

**Comment by LinHuiG** [comment]
确实失效了==

**Comment by CurtisWong458** [comment]
https://github.com/haozi/New-Bing-Anywhere/issues/21#issuecomment-1513861917

**Comment by haozi** [comment]
https://github.com/haozi/New-Bing-Anywhere/issues/19#issuecomment-1513620970

**Comment by haozi** [comment]
1.8.1版本已上架
