### ISSUE TITLE
失效了

### ISSUE THREAD

**Issue by Saniq** [haozi/New-Bing-Anywhere#27]
Version: 1.5.2
UA: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36
Lang: zh-CN
AcceptLangs: zh-CN, en, zh, ru, zh-TW, en-US, en-GB-oxendict

**Comment by haozi** [comment]
https://github.com/haozi/New-Bing-Anywhere/issues/19#issuecomment-1513620970

**Comment by Saniq** [comment]
![image](https://user-images.githubusercontent.com/93535247/234262957-99f917ce-f497-4780-86cb-f9c24ce05715.png)

我用的是谷歌，用的转换器/笑哭

**Comment by haozi** [comment]
1.8.1版本已上架
