### ISSUE TITLE
配合扩展管理器（Extension Manager）的规则会导致chrome异常崩溃

### ISSUE THREAD

**Issue by u2shana** [haozi/New-Bing-Anywhere#31]
![image](https://user-images.githubusercontent.com/14146754/235429676-9195ef81-b784-468e-8aa8-294c9e1cccc0.png)
规则意思大致就是域名匹配上就开启插件,关闭网页后关闭插件

但是添加这规则后,关闭bing的网页时,整个chrome就闪退了

**Comment by haozi** [comment]
This is not our bug,you should contact the corresponding developer. 

By the way, our extension strictly adheres to the principle of minimal permissions and will not request authorization on unnecessary websites (the icon will turn gray).

If you don't trust it, please read the source code or uninstall this extension.
