### ISSUE TITLE
failed in firefox

### ISSUE THREAD

**Issue by ika-zvk** [haozi/New-Bing-Anywhere#33]
Hi contributor, Thanks for this work,

But now firefox with new bing chat cannot be use please

Thank you

**Comment by haozi** [comment]
https://addons.mozilla.org/en-US/firefox/addon/new-bing-anywhere/

<img width="839" alt="image" src="https://user-images.githubusercontent.com/4150641/236993207-3f101223-ed02-4222-9e30-a4d4151414ae.png">

**Comment by ika-zvk** [comment]
it still cannot use.
Thanks 
![Screenshot from 2023-05-10 08-32-19](https://github.com/haozi/New-Bing-Anywhere/assets/121087266/01342fa5-7bb5-40eb-a258-8daf7b8e4a3a)

**Comment by haozi** [comment]
> it still cannot use. Thanks
> 
> ![Screenshot from 2023-05-10 08-34-04](https://user-images.githubusercontent.com/121087266/237255610-cfbf3665-e591-43a2-b4c9-4bd737e54cd0.png)

Stop your adblock add-on and retry

"adblock" will block the https://www.bing.com/rewardsapp/reportActivity request, temporarily or permanently disable "adblock."

see https://github.com/haozi/New-Bing-Anywhere/issues/8

**Comment by ika-zvk** [comment]
fixed now thanks so much
