### ISSUE TITLE
关于New-Bing-Anuwhere使用过程的问题

### ISSUE THREAD

**Issue by starskira** [haozi/New-Bing-Anywhere#34]
第一次使用bing chat，使用插件后能进入bing chat页面但是不管什么时候发什么内容都提示24小时内已达邮件上限，已用魔法，全局代理，除了香港节点能用的节点都试过了

**Comment by starskira** [comment]
显示“很抱歉，你似乎不再有权访问此功能。请几天后再次查看。”

**Comment by haozi** [comment]
关闭一下其他的插件
