### ISSUE TITLE
在edge上使用插件的问题

### ISSUE THREAD

**Issue by starskira** [haozi/New-Bing-Anywhere#36]
不开插件显示“很抱歉，你似乎不再有权访问此功能。请几天后再次查看。”
开了插件就显示“你已达到今天的对话限制。 登录以继续你的聊天。”，然后点登录依然显示同样的提示

**Comment by haozi** [comment]
What about try Edge without this extension?

**Comment by starskira** [comment]
抱歉我不是很会放图
这是开了插件显示的提示信息
![image](https://github.com/haozi/New-Bing-Anywhere/assets/133128006/0ae0f671-3ddd-41dd-ad5b-a48a500cc5bb)

关掉拓展设置之后
![image](https://github.com/haozi/New-Bing-Anywhere/assets/133128006/7918cca9-b4ec-4e9d-9d50-d2e42a1e1d18)
再使用bing chat显示的提示信息
![image](https://github.com/haozi/New-Bing-Anywhere/assets/133128006/27528a95-849e-4df7-bcaf-288c4d0045aa)

如果删掉这个插件，使用edge时没有chat功能

**Comment by haozi** [comment]
change your ip and browser and try again

**Comment by starskira** [comment]
用谷歌试试，弹出如图弹窗
![image](https://github.com/haozi/New-Bing-Anywhere/assets/133128006/e3e05c39-f963-4f73-bdae-475088bd18ba)

然后使用插件显示同样的提示信息
![image](https://github.com/haozi/New-Bing-Anywhere/assets/133128006/0de80e13-501c-4bf9-b623-5f14896f76eb)

**Comment by starskira** [comment]
已经换了ip，重装了插件，现在两个浏览器都弹出同样的提示信息了
![image](https://github.com/haozi/New-Bing-Anywhere/assets/133128006/cc6dc3c7-4a54-427f-b370-616491b7ac30)

**Comment by greatwinner123** [comment]
我也是同意的问题，登陆了显示chat界面但无法进行对话
