### ISSUE TITLE
我在谷歌浏览器装了扩展，但是访问bing.com依然没有CHAT聊天框出现

### ISSUE THREAD

**Issue by swordarms** [haozi/New-Bing-Anywhere#39]
我在谷歌浏览器装了扩展，但是访问bing.com依然没有CHAT聊天框出现，请问这是怎么回事。
我的谷歌版本：版本 113.0.5672.92（正式版本） (arm64)
我的系统 macOS ventura 13.3.1

**Comment by haozi** [comment]
see https://github.com/haozi/New-Bing-Anywhere/issues/8 first
