### ISSUE TITLE
20230329无法使用chrome打开聊天

### ISSUE THREAD

**Issue by qiuleidee** [haozi/New-Bing-Anywhere#4]
无法使用chrome打开聊天

Version: 1.2.0
UA: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36
Lang: zh-CN
AcceptLangs: zh-CN, zh

**Comment by haozi** [comment]
We have tested this platform.
Please try the following steps:

1. Upgrade your browser to the latest version
1. Exclude interference from other extensions
1. Reinstall this extension
1. Make sure that the GFW bypass capability is enabled
1. Visit <https://www.bing.com/?run> once
1. Clear the browser cache and all cookies from bing.com
1. Give us some screenshots

**Comment by qiuleidee** [comment]
![image](https://user-images.githubusercontent.com/85733858/228751198-ff971966-beae-433c-84f0-4b99e95bdc80.png)
仍然不起作用

**Comment by haozi** [comment]
Try searching `edge download` in your browser.
Expect to see `You're already browsing in Microsoft Edge` and `Edg/xxxx` in User-Agent.
And can open <https://www.bing.com/new>

![image](https://user-images.githubusercontent.com/4150641/228780285-44388c81-06a5-4260-998d-4b3faa43cfed.png)

![image](https://user-images.githubusercontent.com/4150641/228781524-d99cd934-c8e9-4c4a-ba8e-2fb77fca8829.png)
