### ISSUE TITLE
仍然跳转到国内版的Microsoft Bing

### ISSUE THREAD

**Issue by ChichenC** [haozi/New-Bing-Anywhere#41]
清理历史记录和cookie且重新启动以后仍然跳转到国内版的Microsoft Bing，vpn正常可用，香港线路天气定位在大埔区

Version: 1.9.2 
UA: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36
Lang: zh-CN
AcceptLangs: zh-TW, zh, zh-CN

**Comment by haozi** [comment]
follow these step https://github.com/haozi/New-Bing-Anywhere/issues/8
and still not work，take some screenshots
