### ISSUE TITLE
network problem

### ISSUE THREAD

**Issue by SharkKoko** [haozi/New-Bing-Anywhere#43]
大佬你好，能帮我看一下有什么解决办法吗？爬完梯子，能进NEW BING界面了，但用不了报错：Sorry, looks like your network settings are preventing access to this feature.

**Comment by haozi** [comment]
see number 8

https://github.com/haozi/New-Bing-Anywhere/issues/8

**Comment by haozi** [comment]
No reply for long days, closed, but if you have any new data you can reopen it
