### ISSUE TITLE
未跳转cn.bing，但仍是国内版(已科学上网，能正常访问google),微软账户设置的地址改不了国外

### ISSUE THREAD

**Issue by redaytob** [haozi/New-Bing-Anywhere#44]
未跳转cn.bing，但仍是国内版(已科学上网，能正常访问google),微软账户设置的地址改不了国外
![image](https://github.com/haozi/New-Bing-Anywhere/assets/85326039/5a8ff410-e8aa-46d9-b950-40dd34cafd32)
![image](https://github.com/haozi/New-Bing-Anywhere/assets/85326039/d7862f27-985f-4103-bc42-75f318871ca7)

**Comment by haozi** [comment]
![image](https://github.com/haozi/New-Bing-Anywhere/assets/4150641/ee58e49a-35cd-4091-a0fe-ffa54dbf47a4)
https://github.com/haozi/New-Bing-Anywhere/issues/8
