### ISSUE TITLE
Readme.md Instruction  To begin with, you need a New Bing account, otherwise it will be downgraded to Old Bing

### ISSUE THREAD

**Issue by tukangcode** [haozi/New-Bing-Anywhere#46]
this my first time actualy put first issue participating project, please your guidance everyone.

Issue :
README.MD Line 20

> To begin with, you need a New Bing account, otherwise it will be downgraded to Old Bing
 Clarify again cause  `downgraded to Old Bing` can  make confusion to user thinking need create new acccount cause microsoft already clear up waitlist everyone can join and enjoy without discrimination. Are this because Bing limited on Mainland CN ?

**Comment by tukangcode** [comment]
thanks for respond ! and have good day for you.

**Comment by haozi** [comment]
The README has updated
