### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by mmdwgb** [haozi/New-Bing-Anywhere#48]
提问后会显示 很抱歉，你已达到可在 24 小时内发送到必应的邮件限制。请稍后回来查看!

Version: 1.10.0 
UA: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36 Edg/113.0.1774.57
Lang: zh-CN
AcceptLangs: zh-CN, en, en-GB, en-US

**Comment by haozi** [comment]
1. change your IP
2. login an account

**Comment by muranhuli** [comment]
> 

与IP和账户没有关系，换成edge浏览器可以正常使用

**Comment by haozi** [comment]
> > 
> 
> 与IP和账户没有关系，换成edge浏览器可以正常使用

Do you have any other plugins installed?

**Comment by muranhuli** [comment]
> > > 
> > 
> > 
> > 与IP和账户没有关系，换成edge浏览器可以正常使用
> 
> Do you have any other plugins installed?

没有别的插件，就是在chrome里面用new bing就会显示次数上限，此时换到edge就可以正常使用，梯子节点，环境都不变，我怀疑是不是这个插件被new bing检测了

**Comment by haozi** [comment]
> 
Try other extensions that have similar functionalities to our extension and see how they work?
