### ISSUE TITLE
如何关闭google切换按钮

### ISSUE THREAD

**Issue by kettly1260** [haozi/New-Bing-Anywhere#5]
我安装了类似的切换油猴插件，这个按钮的存在会影响插件的使用
https://greasyfork.org/zh-CN/scripts/12909-google-baidu-switcher-all-in-one

**Comment by haozi** [comment]
The feature is already in progress, and an additional configuration options page is being added.

**Comment by haozi** [comment]
You will see the configuration page starting from version 1.5.0.
If you want to experience it in advance, you can switch to the canary branch and build it yourself.

<img width="830" alt="image" src="https://user-images.githubusercontent.com/4150641/229530166-88a560ad-c9f6-434f-baa7-8b82df055ba3.png">
