### ISSUE TITLE
为什么ubuntu下开clash不能使用new bing

### ISSUE THREAD

**Issue by Rurouni-z** [haozi/New-Bing-Anywhere#52]
但是在windows下就可以使用了，问题不是关于该项目但是还是想问问库主是怎么在ubuntu下使用的呢

**Comment by haozi** [comment]
<img width="1792" alt="image" src="https://github.com/haozi/New-Bing-Anywhere/assets/4150641/12686455-197f-4a11-95f2-4991389b8d58">

Works well

**Comment by Rurouni-z** [comment]
[下载](https://github.com/Fndroid/clash_for_windows_pkg/releases) 选择 x64 linux 版本 即可  已解决
