### ISSUE TITLE
在谷歌浏览器上使用时，会一直验证是否是真人，导致无法进行聊天

### ISSUE THREAD

**Issue by Peanutsboom** [haozi/New-Bing-Anywhere#54]
Version: 1.10.0 
UA: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36
Lang: en-US
AcceptLangs: en-US, en, zh-CN

**Comment by Peanutsboom** [comment]
已经得到了解决，我在手机上的edge浏览器里使用了newbing，然后在手机上验证了真人，然后在网页中也恢复了正常，但是不能确定这个问题在之后是不是还会出现。

**Comment by haozi** [comment]
give us some picture

**Comment by haozi** [comment]
No reply for long days, closed, but if you have any new data you can reopen it
