### ISSUE TITLE
it is not working, still in bing China

### ISSUE THREAD

**Issue by SophiaP2046** [haozi/New-Bing-Anywhere#55]
Version: 1.10.0 
UA: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36
Lang: en-US
AcceptLangs: en-US, en

**Comment by haozi** [comment]
see https://github.com/haozi/New-Bing-Anywhere/issues/8

An overseas IP is required if you are from mainland China or Russia.

**Comment by haozi** [comment]
No reply for long days, closed, but if you have any new data you can reopen it
