### ISSUE TITLE
控制台报错

### ISSUE THREAD

**Issue by Rurouni-z** [haozi/New-Bing-Anywhere#57]
ip地址是美国，并且没有国内版
![image](https://github.com/haozi/New-Bing-Anywhere/assets/53394846/a8681ecf-9ebd-4e39-a846-1ba15545e99f)
![image](https://github.com/haozi/New-Bing-Anywhere/assets/53394846/94ca584d-1e36-4132-8567-03ed1d24cdcb)

Unsafe attempt to initiate navigation for frame with origin 'https://www.bing.com' from frame with URL 'https://login.microsoftonline.com/common/oauth2/authorize?client_id=9ea1ad79-fdb6-4f9a-8bc3-2b70f96e34c7&response_type=id_token&nonce=8b01b700-3ae7-4d07-8591-4833b982cade&redirect_uri=https%3a%2f%2fwww.bing.com%2forgid%2fidtoken%2fnosignin&scope=openid%20email%20profile%209ea1ad79-fdb6-4f9a-8bc3-2b70f96e34c7/.default&response_mode=form_post&instance_aware=true&msafed=0&prompt=none&state=%7b%22ig%22%3a%226294EDF0AC37413DBF0F0C48AE3F9F0F%22%7d'. The frame attempting navigation of the top-level window is sandboxed, but the flag of 'allow-top-navigation' or 'allow-top-navigation-by-user-activation' is not set.

(anonymous) @ authorize?client_id=9ea1ad79-fdb6-4f9a-8bc3-2b70f96e34c7&response_type=id_token&nonce=8b01b700-3ae7-4d07-8591-4833b982cade&redirect_uri=https%3a%2f%2fwww.bing.com%2forgid%2fidtoken%2fnosignin&scope=openid%20email%20profile%209ea1ad79-fdb6-4f9a-8bc3-2b70f96e34c7/.default&response_mode=form_post&instance_aware=true&msafed=0&prompt=none&state=%7b%22ig%22%3a%226294EDF0AC37413DBF0F0C48AE3F9F0F%22%7d:87
(anonymous) @ authorize?client_id=9ea1ad79-fdb6-4f9a-8bc3-2b70f96e34c7&response_type=id_token&nonce=8b01b700-3ae7-4d07-8591-4833b982cade&redirect_uri=https%3a%2f%2fwww.bing.com%2forgid%2fidtoken%2fnosignin&scope=openid%20email%20profile%209ea1ad79-fdb6-4f9a-8bc3-2b70f96e34c7/.default&response_mode=form_post&instance_aware=true&msafed=0&prompt=none&state=%7b%22ig%22%3a%226294EDF0AC37413DBF0F0C48AE3F9F0F%22%7d:87

Uncaught DOMException: Failed to set the 'href' property on 'Location': The current window does not have permission to navigate the target frame to 'https://login.microsoftonline.com/common/oauth2/authorize?client_id=9ea1ad79-fdb6-4f9a-8bc3-2b70f96e34c7&response_type=id_token&nonce=8b01b700-3ae7-4d07-8591-4833b982cade&redirect_uri=https%3a%2f%2fwww.bing.com%2forgid%2fidtoken%2fnosignin&scope=openid%20email%20profile%209ea1ad79-fdb6-4f9a-8bc3-2b70f96e34c7/.default&response_mode=form_post&instance_aware=true&msafed=0&prompt=none&state=%7b%22ig%22%3a%226294EDF0AC37413DBF0F0C48AE3F9F0F%22%7d&iframe-request-id=797927ad-7732-4a60-a0c9-b8db72871300'.
    at https://login.microsoftonline.com/common/oauth2/authorize?client_id=9ea1ad79-fdb6-4f9a-8bc3-2b70f96e34c7&response_type=id_token&nonce=8b01b700-3ae7-4d07-8591-4833b982cade&redirect_uri=https%3a%2f%2fwww.bing.com%2forgid%2fidtoken%2fnosignin&scope=openid%20email%20profile%209ea1ad79-fdb6-4f9a-8bc3-2b70f96e34c7/.default&response_mode=form_post&instance_aware=true&msafed=0&prompt=none&state=%7b%22ig%22%3a%226294EDF0AC37413DBF0F0C48AE3F9F0F%22%7d:87:326
    at https://login.microsoftonline.com/common/oauth2/authorize?client_id=9ea1ad79-fdb6-4f9a-8bc3-2b70f96e34c7&response_type=id_token&nonce=8b01b700-3ae7-4d07-8591-4833b982cade&redirect_uri=https%3a%2f%2fwww.bing.com%2forgid%2fidtoken%2fnosignin&scope=openid%20email%20profile%209ea1ad79-fdb6-4f9a-8bc3-2b70f96e34c7/.default&response_mode=form_post&instance_aware=true&msafed=0&prompt=none&state=%7b%22ig%22%3a%226294EDF0AC37413DBF0F0C48AE3F9F0F%22%7d:87:330
(anonymous) @ authorize?client_id=9ea1ad79-fdb6-4f9a-8bc3-2b70f96e34c7&response_type=id_token&nonce=8b01b700-3ae7-4d07-8591-4833b982cade&redirect_uri=https%3a%2f%2fwww.bing.com%2forgid%2fidtoken%2fnosignin&scope=openid%20email%20profile%209ea1ad79-fdb6-4f9a-8bc3-2b70f96e34c7/.default&response_mode=form_post&instance_aware=true&msafed=0&prompt=none&state=%7b%22ig%22%3a%226294EDF0AC37413DBF0F0C48AE3F9F0F%22%7d:87
(anonymous) @ authorize?client_id=9ea1ad79-fdb6-4f9a-8bc3-2b70f96e34c7&response_type=id_token&nonce=8b01b700-3ae7-4d07-8591-4833b982cade&redirect_uri=https%3a%2f%2fwww.bing.com%2forgid%2fidtoken%2fnosignin&scope=openid%20email%20profile%209ea1ad79-fdb6-4f9a-8bc3-2b70f96e34c7/.default&response_mode=form_post&instance_aware=true&msafed=0&prompt=none&state=%7b%22ig%22%3a%226294EDF0AC37413DBF0F0C48AE3F9F0F%22%7d:87

Version: 2.0.1 
UA: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36
Lang: zh-CN
AcceptLangs: zh-CN, zh
config: {"showGoogleButtonOnBing":true,"showBingButtonOnGoogle":true,"showGuideToGithub":false,"showChat":true,"triggerMode":"Always","conversationStyle":"Balanced"}

**Comment by Rurouni-z** [comment]
An iframe which has both allow-scripts and allow-same-origin for its sandbox attribute can escape its sandboxing.
重新登录之后，有这个warning，并且没有聊天选项

**Comment by Rurouni-z** [comment]
进入bing.com/?/ai 网址报错
[Report Only] Refused to load the script 'https://www.bing.com/rp/lmu8EBCaPRMKtay8LSArGyY3mv4.br.js' because it violates the following Content Security Policy directive: "script-src https: 'strict-dynamic' 'report-sample' 'nonce-tQTtQ2aSZfXrccbNfohXoMmoLaB9j7E+qp4cGAhlK/U='". Note that 'strict-dynamic' is present, so host-based allowlisting is disabled. Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.

DevTools failed to load source map: Could not load content for https://www.bing.com/rp/preact.umd.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

The resource https://www.bing.com/rp/lmu8EBCaPRMKtay8LSArGyY3mv4.br.js was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.

**Comment by Rurouni-z** [comment]
![image](https://github.com/haozi/New-Bing-Anywhere/assets/53394846/9ff9d84b-7c69-4f2d-adb4-1b09860deaed)

**Comment by Rurouni-z** [comment]
解决了，要开启全局代理，而且必须是美国

**Comment by Rurouni-z** [comment]
![image](https://github.com/haozi/New-Bing-Anywhere/assets/53394846/702b196b-3983-4d86-bae1-7ac06035109e)

**Comment by haozi** [comment]
确保 www.bing.com / sydney.bing.com 走的是代理

**Comment by Rurouni-z** [comment]
> 确保 `www.bing.com / sydney.bing.com` 两个域名走的是代理

![image](https://github.com/haozi/New-Bing-Anywhere/assets/53394846/20b76941-a17f-400c-9051-0b7c519a7471)

**Comment by haozi** [comment]
试一下纯净的edge浏览器呢

**Comment by Rurouni-z** [comment]
> 试一下纯净的edge浏览器呢

也不行。。newbing与我无缘，有好用的网页gpt推荐吗
