### ISSUE TITLE
搜索栏旁边的 new bing 出现错误

### ISSUE THREAD

**Issue by Langeeker** [haozi/New-Bing-Anywhere#59]
搜索栏旁边的 new bing 出现错误：
Error: There seem to be some errors :SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON
config: {"showGoogleButtonOnBing":true,"showBingButtonOnGoogle":true,"showGuideToGithub":true,"showChat":true,"triggerMode":"Always","conversationStyle":"Balanced"}
engine: google
query: name

**Comment by haozi** [comment]
下面有列出解决方案引导
![image](https://github.com/haozi/New-Bing-Anywhere/assets/4150641/a6afd08e-41c8-4d63-85e2-a8ed328a4d1b)

**Comment by Langeeker** [comment]
> 下面有列出解决方案引导 ![image](https://user-images.githubusercontent.com/4150641/246354728-a6afd08e-41c8-4d63-85e2-a8ed328a4d1b.png)

全部检查过了没有问题才提交的 issue，单击 bing 图标可以正常跳转聊天，账户也登录了。只有右边这个回答框出现问题，多次刷新和重装没有用。可以设置一个选项关闭这个吗？ （If it remains unresolved, please [submit an issue](https://github.com/haozi/New-Bing-Anywhere/issues) to us.）

**Comment by Langeeker** [comment]
> 下面有列出解决方案引导 ![image](https://user-images.githubusercontent.com/4150641/246354728-a6afd08e-41c8-4d63-85e2-a8ed328a4d1b.png)

另外，我的错误显示：Error: There seem to be some errors :SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON 不是 object Event

**Comment by Langeeker** [comment]
<img width="413" alt="123" src="https://github.com/haozi/New-Bing-Anywhere/assets/41421063/7db11596-a178-431e-9540-feed410b819c">

**Comment by haozi** [comment]
有关闭选项啊，点齿轮进去

**Comment by Langeeker** [comment]
> 有关闭选项啊，点齿轮进去 ![image](https://user-images.githubusercontent.com/4150641/246377907-229d2d33-6a23-45e7-9c70-bc59f36e7ac7.png)
> 
> ![image](https://user-images.githubusercontent.com/4150641/246378022-5f39bdf2-4667-4ddf-b546-ba76f47131a1.png) ![image](https://user-images.githubusercontent.com/4150641/246378076-1415d623-818e-40b3-8b2c-474fea067a5c.png)

我打不开插件的 option 选项页面，一直在转圈： 
<img width="503" alt="222" src="https://github.com/haozi/New-Bing-Anywhere/assets/41421063/ff443d70-7122-49bf-9b80-6150d4fc9a2f">

**Comment by haozi** [comment]
点齿轮，这个已知bug，这周末会修掉
