### ISSUE TITLE
不开vpn还是会重定向到cn.bing

### ISSUE THREAD

**Issue by wangziyo** [haozi/New-Bing-Anywhere#6]
用chrome会显示重定向次数过多，用edge会重定向到cn.bing我是通过插件的按钮直接点的。网络是广东联通

**Comment by haozi** [comment]
1. Make sure you are logged into your New Bing account
1. Make sure that the GFW bypass capability is enabled
1. Upgrade your browser to the latest version
2. Exclude interference from other extensions
Reinstall this extension
1. Visit https://www.bing.com/?run once or clear the browser cache and all cookies from bing.com
1. Give us some screenshots

**Comment by wangziyo** [comment]
![捕获1](https://user-images.githubusercontent.com/104545723/229016695-c015d07e-03f5-453e-8c82-ffb86349c3b1.PNG)
![19d9bf67acadc3bd831715d9eb99384](https://user-images.githubusercontent.com/104545723/229016725-3ed102f8-ec25-4ebc-ac08-98191d2d106d.png)
![99607f1d96f21b8c373adc67ae3efba](https://user-images.githubusercontent.com/104545723/229016735-c182bb9f-4de0-4ef2-bd46-7df5e2cfffc0.png)
如图，最新版本，其他插件都没开，通过按钮点击访问的，还是重定向了，我打开vpn插件是能访问的

**Comment by haozi** [comment]
Try installing the international version of Edge, not the China-specific version. 
Do not set the region of your Windows to mainland China.
Additionally, are there a lot of redirects in Chrome?

**Comment by wangziyo** [comment]
![image](https://user-images.githubusercontent.com/104545723/229039052-a1d14408-ed7a-407a-8f4f-d08e0ac696fb.png)
![image](https://user-images.githubusercontent.com/104545723/229039140-51d15f20-f198-4aca-83ea-5ddf0b9f1477.png)
![image](https://user-images.githubusercontent.com/104545723/229039195-8c465300-7c0b-49c4-8a13-272364621332.png)
我的地区一直是这么设置的，用chrome就会出现这个错误

**Comment by haozi** [comment]
Show me your request header(but please make sure not to reveal the cookie section).

**Comment by wangziyo** [comment]
![image](https://user-images.githubusercontent.com/104545723/229044400-ef86bac2-98e7-4b51-8c31-e8814f286841.png)

**Comment by haozi** [comment]
This seems to be a problem, but I am unable to reproduce it.

**Comment by fhwhite** [comment]
不只是不开不行，开错了都不行，我有两个韩国甲骨文xray，其中一个不知道原因访问不了newbing，另一个可以

开edge能访问newbing的节点，chrome完美访问newbing

开edge不能访问newbing的节点，会自动跳转到国内版 国际版那个页面

**Comment by haozi** [comment]
![IMG_9953](https://user-images.githubusercontent.com/4150641/229352081-6748d3ef-5291-418f-8bad-b97a4e16054c.jpg)
