### ISSUE TITLE
很抱歉，你已达到可在 24 小时内发送到必应的邮件限制。请稍后回来查看!

### ISSUE THREAD

**Issue by Hendry5479** [haozi/New-Bing-Anywhere#62]
刚登录就这样

Version: 2.0.2 
UA: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36
Lang: en-US
AcceptLangs: zh-CN, zh, zh-HK
config: {"showGoogleButtonOnBing":true,"showBingButtonOnGoogle":true,"showGuideToGithub":true,"showChat":true,"triggerMode":"Always","conversationStyle":"Balanced"}

**Comment by haozi** [comment]
change a Microsoft account

**Comment by haozi** [comment]
No reply for long days, closed, but if you have any new data you can reopen it
