### ISSUE TITLE
开了全局都提示在国内。

### ISSUE THREAD

**Issue by rebron1900** [haozi/New-Bing-Anywhere#64]
FAQ里的情况都一一确认过。

Version: 2.0.2 
UA: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36
Lang: zh-CN
AcceptLangs: zh, zh-CN
config: {"showGoogleButtonOnBing":true,"showBingButtonOnGoogle":true,"showGuideToGithub":false,"showChat":true,"triggerMode":"Always","conversationStyle":"Balanced"}

**Comment by haozi** [comment]
看你的梯子配置，开了全局不等于流量都走到了代理

**Comment by rebron1900** [comment]
下面两种方法我都测试了，还是不行：
1. 我把FAQ里的两个域名都放规则里
2. 开全局模式

**Comment by OiCkilL** [comment]
我也有一样的问题

**Comment by ZiMoFangCong** [comment]
清除你的bing cookie
