### ISSUE TITLE
村BA

### ISSUE THREAD

**Issue by Sureeee** [haozi/New-Bing-Anywhere#65]
Version: 2.0.2 
UA: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36
Lang: zh-CN
AcceptLangs: zh-CN, zh
config: {"showGoogleButtonOnBing":true,"showBingButtonOnGoogle":true,"showGuideToGithub":true,"showChat":true,"triggerMode":"Always","conversationStyle":"Balanced"}
engine: google
query: 村ba

**Comment by haozi** [comment]
Incomprehensible, closed, but if you have any new data you can reopen it
