### ISSUE TITLE
Sorry, looks like your network settings are preventing access to this feature.

### ISSUE THREAD

**Issue by bangbangda** [haozi/New-Bing-Anywhere#67]
1. 所有插件都关闭了 只保留newbing
2. 代理开了 域名也检测了都走代理
3. 可以看下搜索天气也是伦敦了

但是还提示网络问题 有可能是什么原因呢？

![WX20230620-232910@2x](https://github.com/haozi/New-Bing-Anywhere/assets/13864407/59039e14-0720-4da0-9ed2-aec7bcf53845)
![WX20230620-232709@2x](https://github.com/haozi/New-Bing-Anywhere/assets/13864407/da169170-0a3a-4697-a26d-b39671d66f69)
![WX20230620-232640@2x](https://github.com/haozi/New-Bing-Anywhere/assets/13864407/db546014-48d5-4885-ab3e-875862d96ee1)
![WX20230620-232612@2x](https://github.com/haozi/New-Bing-Anywhere/assets/13864407/f543d0b9-31a9-4011-8b3f-d725eb1c612c)

Version: 2.0.2 
UA: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36
Lang: zh-CN
AcceptLangs: en, zh-CN, zh
config: {"showGoogleButtonOnBing":true,"showBingButtonOnGoogle":false,"showGuideToGithub":true,"showChat":true,"triggerMode":"Always","conversationStyle":"Balanced"}

**Comment by haozi** [comment]
```
"Sorry, looks like your network settings are preventing access to this feature." 抱歉，您的网络设置似乎阻止访问此功能
You have enabled X-Forwarded-For header in other extensions that modify the request header, find and disable it. (In future versions, we will consider automatically deleting this request header)
您在其他插件里开启了使用 X-Forwarded-For 功能，找到并关闭它。这已经是一个过时的教程。(在未来版本里，我们会考虑自动删除这个可能的请求头)
```

if still not work ，try Edge without any extensions or change your IP
