### ISSUE TITLE
还是不能显示国内国外，翻墙已经正常显示洛杉矶IP，并且谷歌正常能搜索了，但是就是不能使用BING CHAT.好像有一个电信宽带是OK，但是联通宽带不行。

### ISSUE THREAD

**Issue by fnpkcs2023** [haozi/New-Bing-Anywhere#68]
显示洛杉矶IP，并且谷歌正常能搜索了，但是就是不能使用BING CHAT.好像有一个电信宽带是OK，但是联通宽带不行。

Version: 2.0.2 
UA: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36
Lang: zh-CN
AcceptLangs: zh-CN, zh
config: {"showGoogleButtonOnBing":true,"showBingButtonOnGoogle":true,"showGuideToGithub":false,"showChat":true,"triggerMode":"Always","conversationStyle":"Balanced"}

**Comment by haozi** [comment]
Thanks for your analysis
