### ISSUE TITLE
无法使用bing ai

### ISSUE THREAD

**Issue by yaokmallorca** [haozi/New-Bing-Anywhere#70]
Version: 0.2.0.2 (Canary) 
UA: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36
Lang: en-US
AcceptLangs: en-GB, zh-CN, zh, es-ES, es, en-US, en
config: {"showGoogleButtonOnBing":true,"showBingButtonOnGoogle":true,"showGuideToGithub":true,"showChat":true,"triggerMode":"Always","conversationStyle":"Balanced"}

**Comment by haozi** [comment]
Incomprehensible, closed, but if you have any new data you can reopen it
