### ISSUE TITLE
Chrome 中 google 的 new bing anywhere sidebar，无论如何刷新均卡在"Sending prompt to Bing..."上

### ISSUE THREAD

**Issue by mzw222** [haozi/New-Bing-Anywhere#71]
如topic, 是在 google 中使用 new bing anywhere sidebar
很偶尔几次能成功，但多数情况下都是到"Sending prompt to Bing..."就再没反应；
但单纯打开及使用 bing.com 是没问题的

尝试过开着 bing.com（已登入）同时再尝试使用sidebar, 但仍然是卡死的⋯⋯

Browser: Chrome in latest version
MacOS PC

**Comment by mzw222** [comment]
正常的！

**Comment by mzw222** [comment]
以及由今天开始 side bar 就直接显示 error 了，如下

Error: There seem to be some errors:SyntaxError: Unexpected end of JSON input

You can try the following methods to fix them:
If you are using browsers like Brave, please make sure you have allowed third-party cookies for the domain `*.google.com`.
Make sure you have successfully logged in to your Microsoft account on [Bing.com](https://www.bing.com/).
There might be a Network Error, if you are from a country or region that does not support the New Bing Chat. You may need to configure a network proxy correctly. Refer to [<Configure the Network Proxy>](https://github.com/haozi/New-Bing-Anywhere/issues/8) for more information.
Click the force refresh button in the top right corner and try again.
If it remains unresolved, please [submit an issue](https://github.com/haozi/New-Bing-Anywhere/issues) to us.

**Comment by haozi** [comment]
抓包看下这两个请求

![image](https://github.com/haozi/New-Bing-Anywhere/assets/4150641/72ee013c-a0c4-459e-ba15-e176e74a0557)

**Comment by mzw222** [comment]
现在是这样（

<img width="1503" alt="Screenshot 2023-06-27 at 9 31 00 PM" src="https://github.com/haozi/New-Bing-Anywhere/assets/96655554/112d17b6-90ca-43e7-8493-b2bf0259b3ff">
<img width="1503" alt="Screenshot 2023-06-27 at 9 31 08 PM" src="https://github.com/haozi/New-Bing-Anywhere/assets/96655554/111a8456-86da-4ad1-b41d-2059c184dba8">
![Uploading Screenshot 2023-06-27 at 9
<img width="1503" alt="Screenshot 2023-06-27 at 9 31 12 PM" src="https://github.com/haozi/New-Bing-Anywhere/assets/96655554/b50e4aeb-9372-4e1a-a67c-db550806ea56">
.31.10 PM.png…]()
<img width="1503" alt="Screenshot 2023-06-27 at 9 31 16 PM" src="https://github.com/haozi/New-Bing-Anywhere/assets/96655554/e42c0ce2-1305-4fe2-b7d9-5d1e3c51cc93">

**Comment by mzw222** [comment]
现在是这样（

<img width="1503" alt="Screenshot 2023-06-27 at 9 31 00 PM" src="https://github.com/haozi/New-Bing-Anywhere/assets/96655554/14189957-8671-49e5-af8b-738464f53693">
<img width="1503" alt="Screenshot 2023-06-27 at 9 31 08 PM" src="https://github.com/haozi/New-Bing-Anywhere/assets/96655554/975d8e4e-b7c7-4c81-a9a9-5a9d7fa90f75">
<img width="1503" alt="Screenshot 2023-06-27 at 9 31 10 PM" src="https://github.com/haozi/New-Bing-Anywhere/assets/96655554/56d24347-f73e-4dbb-8c42-b7f40057cec1">
<img width="1503" alt="Screenshot 2023-06-27 at 9 31 12 PM" src="https://github.com/haozi/New-Bing-Anywhere/assets/96655554/0092f088-df75-44f9-ba70-336f6047d333">
<img width="1503" alt="Screenshot 2023-06-27 at 9 31 16 PM" src="https://github.com/haozi/New-Bing-Anywhere/assets/96655554/11200fc4-c095-49b1-adcd-34b4d055caca">

**Comment by haozi** [comment]
看一下create请求的请求头中有没有带cookie，应该是静止了Google.com 域名的第三方cookie，查一下相关设置和相关插件

**Comment by mzw222** [comment]
！调整了一些chrome插件，已解决，谢谢～
