### ISSUE TITLE
Error: There seem to be some errors :Request is throttled. Please try again later.

### ISSUE THREAD

**Issue by xjiaqing** [haozi/New-Bing-Anywhere#73]
Error: There seem to be some errors :Request is throttled. Please try again later.

Version: 2.0.2 
UA: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36 Edg/114.0.1823.58
Lang: zh-CN
AcceptLangs: zh-CN, en-US
config: {"showGoogleButtonOnBing":true,"showBingButtonOnGoogle":true,"showGuideToGithub":true,"showChat":true,"triggerMode":"Always","conversationStyle":"Balanced"}

**Comment by haozi** [comment]
change a MS ACCOUNT

**Comment by haozi** [comment]
long time no reply, close it
