### ISSUE TITLE
插件工作异常

### ISSUE THREAD

**Issue by mengjincc** [haozi/New-Bing-Anywhere#74]
已经可以访问正常的new bing 但是插件工作还是不正常。不知道原因是什么。
![image](https://github.com/haozi/New-Bing-Anywhere/assets/25782812/c60f39a2-d494-4a21-a2a8-a6a5f23b10a7)
 

Version: 2.0.2 
UA: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36
Lang: zh-CN
AcceptLangs: zh-CN, zh
config: {"showGoogleButtonOnBing":true,"showBingButtonOnGoogle":true,"showGuideToGithub":true,"showChat":true,"triggerMode":"Always","conversationStyle":"Balanced"}
engine: google
query: hack new bing

**Comment by haozi** [comment]
Incomprehensible, closed, but if you have any new data you can reopen it
