### ISSUE TITLE
My ip is in United States, but I still can't use new bing,why?明明ip是在美国啊，为什么还是无法使用new bing？

### ISSUE THREAD

**Issue by yui34567** [haozi/New-Bing-Anywhere#75]
![image](https://github.com/haozi/New-Bing-Anywhere/assets/33209218/d19bfcc0-134d-4e7d-b7d6-d08f72291666)
明明ip是在美国啊，为什么还是无法使用new bing？
My ip is in United States, but I can't use new bing,why?

**Comment by haozi** [comment]
https://github.com/haozi/New-Bing-Anywhere/issues/8
1. 装了插件不跳转 cn 二级域名了，但还是显示国内版/国际版
A: 对于中国大陆及俄罗斯用户，现在必须使用海外 IP。如果你使用了 Clash 等工具，确保 www.bing.com / sydney.bing.com 走的不是直连(由于这个域名可用，默认没进特殊规则列表)。

4.如何确定我是否科学上网成功？
A: 必应搜索「天气」，看下是否默认定位到境外的城市；搜索一些特别关键词，看是否出现大尺度内容。用必应搜！用必应搜！！用必应搜！！！不是谷歌不是百度...

**Comment by haozi** [comment]
long time no reply, close it
