### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by 1530426574** [haozi/New-Bing-Anywhere#78]
Version: 2.0.2 
UA: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36
Lang: zh-CN
AcceptLangs: zh-CN, en-US, zh
config: {"showGoogleButtonOnBing":true,"showBingButtonOnGoogle":true,"showGuideToGithub":true,"showChat":true,"triggerMode":"Always","conversationStyle":"Balanced"}
engine: google
query: python 读取word图片和文字

**Comment by haozi** [comment]
Incomprehensible, closed, but if you have any new data you can reopen it
