### ISSUE TITLE
can't chat

### ISSUE THREAD

**Issue by Johnvalosky** [haozi/New-Bing-Anywhere#79]
插件没什么问题但是每次去bing ai问问题在第一个问题就会提示Sorry, you've reached the limit of messages. 不知道是否有什么办法绕过ms的limit，还是说是这玩意的bug
还有就是在bing chat里登录之后，刷新之后又会说Sign in to ask more questions and have longer conversations

Version: 2.0.2 
UA: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36 Edg/114.0.1823.67
Lang: en-US
AcceptLangs: en-US, en
config: {"showGoogleButtonOnBing":true,"showBingButtonOnGoogle":true,"showGuideToGithub":false,"showChat":true,"triggerMode":"Always","conversationStyle":"Balanced"}

**Comment by haozi** [comment]
Change a MS account

**Comment by Johnvalosky** [comment]
thanks, my other account works, seems that the original account is blocked lol

**Comment by king0billy** [comment]
> thanks, my other account works, seems that the original account is blocked lol谢谢，我的另一个帐户有效，似乎原始帐户被阻止了哈哈

我也一样
