### ISSUE TITLE
SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by MichaelToLearn** [haozi/New-Bing-Anywhere#85]
Version: 2.0.2 
UA: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36
Lang: zh-CN
AcceptLangs: zh-CN, zh, en, en-US, zh-TW
config: {"showGoogleButtonOnBing":true,"showBingButtonOnGoogle":true,"showGuideToGithub":false,"showChat":true,"triggerMode":"Always","conversationStyle":"Balanced"}
engine: google
query: chrome 修改快捷方式图标

```
New Bing Anywhere
Error: There seem to be some errors :SyntaxError: Unexpected end of JSON input

You can try the following methods to fix them:

If you are using browsers like Brave, please make sure you have allowed third-party cookies for the domain `*.google.com`.
Make sure you have successfully logged in to your Microsoft account on [Bing.com](https://www.bing.com/).
There might be a Network Error, if you are from a country or region that does not support the New Bing Chat. You may need to configure a network proxy correctly. Refer to [<Configure the Network Proxy>](https://github.com/haozi/New-Bing-Anywhere/issues/8) for more information.
Click the force refresh button in the top right corner and try again.
If it remains unresolved, please [submit an issue](https://github.com/haozi/New-Bing-Anywhere/issues) to us.
```

**Comment by haozi** [comment]
Please upgrade new version, the error information will more clear

https://chrome.google.com/webstore/detail/new-bing-anywhere-bing-ch/hceobhjokpdbogjkplmfjeomkeckkngi/reviews?hl=en
