### ISSUE TITLE
还是不行

### ISSUE THREAD

**Issue by 20130216** [haozi/New-Bing-Anywhere#89]
刚才还能用，现在又不能用了！
显示“ Sorry, looks like your network settings are preventing access to this feature.”
不知道哪里出错了
<img width="951" alt="image" src="https://github.com/haozi/New-Bing-Anywhere/assets/138884894/eee38e5c-3114-45b6-b1e1-b15ff9c73ae0">

Version: 2.0.2 
UA: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36 Edg/116.0.0.0
Lang: zh-CN
AcceptLangs: zh-CN, en-US, en, en-GB
config: {"showGoogleButtonOnBing":true,"showBingButtonOnGoogle":true,"showGuideToGithub":true,"showChat":true,"triggerMode":"Always","conversationStyle":"Balanced"}

**Comment by haozi** [comment]
try this one https://github.com/haozi/New-Bing-Anywhere/releases/tag/v2.1.2

**Comment by 20130216** [comment]
好了。但是侧边栏一直没法用！为啥左侧可以，但侧边栏一直有问题呢
