### ISSUE TITLE
地址设置都是对的，为啥还是显示“Sorry, looks like your network settings are preventing access to this feature.”

### ISSUE THREAD

**Issue by 20130216** [haozi/New-Bing-Anywhere#90]
地址设置如下：
<img width="235" alt="image" src="https://github.com/haozi/New-Bing-Anywhere/assets/138884894/e9ed5b6a-e975-4da3-b1b2-32885a047192">

信箱是gmail信箱 安装了“new bing anywhere”等3个插件 依然无法使用
<img width="878" alt="image" src="https://github.com/haozi/New-Bing-Anywhere/assets/138884894/89411dc6-9d0a-45d4-8d09-acad96ac20a8">

Version: 2.0.2 
UA: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36 Edg/116.0.0.0
Lang: zh-CN
AcceptLangs: zh-CN, en-US, en, en-GB
config: {"showGoogleButtonOnBing":true,"showBingButtonOnGoogle":true,"showGuideToGithub":true,"showChat":true,"triggerMode":"Always","conversationStyle":"Balanced"}

**Comment by haozi** [comment]
https://github.com/haozi/New-Bing-Anywhere/issues/8

**Comment by 20130216** [comment]
<img width="785" alt="image" src="https://github.com/haozi/New-Bing-Anywhere/assets/138884894/24191f3e-ca30-447f-b2bb-1c38d988d378">
1. 所有插件都不可用吗
2. 还是前两个插件不可用，只用这个就可以了？

**Comment by haozi** [comment]
文档不能自己读一读，我是你客服？
