### ISSUE TITLE
Error: User needs to solve CAPTCHA to continue.

### ISSUE THREAD

**Issue by TD2775** [haozi/New-Bing-Anywhere#93]
使用过程中会提示人机验证;错误提示如下:

Error: There seem to be some errors :User needs to solve CAPTCHA to continue.

You can try the following methods to fix them:

Make sure you have successfully logged into your Microsoft account on [Bing.com](https://www.bing.com/). And ensure that the MS account is not banned (able to chat successfully on [Bing-chat](https://www.bing.com/search?q=Bing+AI&showconv=1&FORM=hpcodx)).
If you are using browsers like Brave, please make sure you have allowed third-party cookies for the domain `*.google.com`.
There might be a Network Error, if you are from a country or region that does not support the New Bing Chat. You may need to configure a network proxy correctly. Refer to [<Configure the Network Proxy>](https://github.com/haozi/New-Bing-Anywhere/issues/8) for more information.
Click the force refresh button in the top right corner and try again.
If it remains unresolved, please

<pre>
Version: 2.1.4 
UA: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36
Lang: zh-CN
AcceptLangs: zh-CN, zh
config: {"showGoogleButtonOnBing":true,"showBingButtonOnGoogle":true,"showGuideToGithub":true,"showChat":true,"showRelease":true,"triggerMode":"Always","conversationStyle":"Balanced"}
engine: google
query: 并查集
stack: Error: User needs to solve CAPTCHA to continue.
</pre>

**Comment by haozi** [comment]
Your account may be newly registered or blocked, change to another account, or train for a period of time.

**Comment by fredericky123** [comment]
能不能在sidebar弹出窗口进行验证
现在只能打开原生的bing chat窗口 点击进行验证

**Comment by haozi** [comment]
> 能不能在sidebar弹出窗口进行验证 现在只能打开原生的bing chat窗口 点击进行验证

Validation  at https://www.bing.com/search?q=Bing+AI&showconv=1

**Comment by fredericky123** [comment]
> > 能不能在sidebar弹出窗口进行验证 现在只能打开原生的bing chat窗口 点击进行验证
> 
> Validation at https://www.bing.com/search?q=Bing+AI&showconv=1

是的，每次都得到这个页面验证，想的是如果在搜索的侧边栏能直接验证就好了

**Comment by haozi** [comment]
> > > 能不能在sidebar弹出窗口进行验证 现在只能打开原生的bing chat窗口 点击进行验证
> > 
> > 
> > Validation at https://www.bing.com/search?q=Bing+AI&showconv=1
> 
> 是的，每次都得到这个页面验证，想的是如果在搜索的侧边栏能直接验证就好了

Nurtur the account for a period of time

**Comment by haozi** [comment]
The CAPTCHA challenge is difficult to solve. Microsoft has outsourced it to Cloudflare, so the only way to resolve it is within Bing's own chat box.
