### ISSUE TITLE
如果能配合侧边翻译就更好了 听说有点难

### ISSUE THREAD

**Issue by thomasTAT** [haozi/New-Bing-Anywhere#95]
https://chrome.google.com/webstore/detail/edge-translate/bocbaocobfecmglnmeaeppambideimao?hl=zh-CN

![image](https://github.com/haozi/New-Bing-Anywhere/assets/109513632/0b3c9521-66c3-4f61-89c9-d4a741fc8bdd)
![image](https://github.com/haozi/New-Bing-Anywhere/assets/109513632/c99bd49d-eaa2-40e1-bec5-c140b7c9627a)

<pre>
Version: 2.1.4 
UA: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36 Edg/114.0.1823.67
Lang: zh-CN
AcceptLangs: zh-TW, en
config: {"showGoogleButtonOnBing":true,"showBingButtonOnGoogle":true,"showGuideToGithub":true,"showChat":true,"showRelease":true,"triggerMode":"Always","conversationStyle":"Creative"}
engine: google
query: vpn only apply certain website

conversation: https://sydney.bing.com/sydney/GetConversation?conversationId=51D%7CBingProd%7C6BFF22CD6BD678DF36A38D1E6B9900700B74C32E851B1B8D38BCA25E814E55DC&source=cib&participantId=914801440912803&conversationSignature=bDTBd3c%2FIHtXJJPQtdQ05m29GS03am9dodu1D93DBtE%3D</pre>

**Comment by haozi** [comment]
Can't do it, NBA's sidebar is in a sandbox
