### ISSUE TITLE
add an opiton to choose a conversation style

### ISSUE THREAD

**Issue by dyjeong365** [haozi/New-Bing-Anywhere#96]
Hello, I love your New-Bing-Anywhere extension. 

This is a **feature request**. I would appreciate it if you could review and add my suggestions.

- add an option to choose a conversation style (e.g, creative, balanced ...)
- add the ability to suggest anticipatory questions like the original bingChat
  - <img width="547" alt="anticipatory-questions" src="https://github.com/haozi/New-Bing-Anywhere/assets/1175328/24fa33fa-c3c2-4334-9e4c-a093befdd7e6">

**Comment by haozi** [comment]
These function is available, in the sidebar settings

![image](https://github.com/haozi/New-Bing-Anywhere/assets/4150641/b3252e5c-f844-4db2-ae10-ed4d0e5d9c2e)
![image](https://github.com/haozi/New-Bing-Anywhere/assets/4150641/53381114-38af-454f-9c6e-21ccf41fc445)

![image](https://github.com/haozi/New-Bing-Anywhere/assets/4150641/f7d80100-c8ef-4a20-ae8c-564ca110eab5)

**Comment by haozi** [comment]
Our current version does not support www.google.co.kr
You can use www.google.com or wait for our later version, more Google domains will be supported.

You can visit https://www.google.com/ncr once, and you will not be redirected to the Google's national domain name.
