### ISSUE TITLE
插件无法生效

### ISSUE THREAD

**Issue by matt-sun** [haozi/New-Bing-Anywhere#99]
<pre>
Version: 2.1.4 
UA: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36
Lang: zh-CN
AcceptLangs: zh, zh-CN
config: {"showGoogleButtonOnBing":true,"showBingButtonOnGoogle":true,"showGuideToGithub":false,"showChat":true,"showRelease":true,"triggerMode":"Always","conversationStyle":"Balanced"}
engine: google
query: 哈哈哈
stack: Error: Error: Failed to create session.Please ensure that the `https://www.bing.com/turing/conversation/create` request is accessible.
</pre>

**Comment by haozi** [comment]
写的这么清楚了都

**Comment by haozi** [comment]
https://github.com/haozi/New-Bing-Anywhere/issues/101
